name: ThePlazza Compile

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3

      - name: Make all
        run: make re

      - name: Make tests
        run: make tests_run
